# Segunda Avaliação de Física Computacional I¶

* Aluno : Gabriel Wendell Celestino Rocha
* Matrícula :  20190112149 

* Disciplina : Física Computacional I
* Professor : Leonardo Machado
* Data de Entrega : 13/11/2020

In [1]:
import numpy as np
import time

## Problema 5.

### Letra a)

Desejamos resolver o sistema abaixo utilizando método de Gauss-Jordan:

$$2w+x+4y+z=-4$$

$$3w+4x-y-z=3$$

$$w-4x+y+5z=9$$

$$2w-2x+y+3z=7$$

Primeiramente vamos definir nossa matriz `A` e nosso vetor coluna `v`:

In [2]:
A = np.matrix([[2, 1, 4, 1],
              [3, 4,-1,-1],
              [1,-4, 1, 5],
              [2,-2, 1, 3]],float)  
v = np.array([-4,3,9,7],float)

N = len(v)
x = np.zeros(N)

Agora definimos uma função que chamaremos de `GaussJordan(A,v)` que irá implementar o método de eliminação de Gauss-Jordan:

In [3]:
def GaussJordan(A,v):
    k = 0
    for i in range(N):
        if A[i,i]==0:
            while k < N-2:
                if A[k+1,i]>A[k,k]:
                    aux_x = A[k+1,:]
                    A[k+1,:] = A[k,:] 
                    A[k,:] = aux_x
                    
                    row_number = k+1
                k += 1
        else:
            v[i] = v[i]/A[i,i]
            A[i,:] = A[i,:]/A[i,i]
            for j in range(i+1,N):
                mult = -(A[j,i])/A[i,i]
                A[j,:] = A[j,:] + mult*A[i,:]
                v[j] = v[j] + mult*v[i]

    v[N-1] = v[N-1]/A[N-1,N-1]
    A[N-1,N-1] = 1.0
    
    for k in range(N-1):
        for p in range(k+1,N):
            mult = -(A[k,p])
            A[k,:] = A[k,:] + mult*A[p,:]
            v[k] = v[k] + mult*v[p]

    return v;

Agora usamos a nossa função para resolver o sistema proposto na questão:

In [4]:
print("- Solução: \n")
print(GaussJordan(A,v),"\n")
print('- Matriz Diagonal: \n')
print(A)

- Solução: 

[ 2. -1. -2.  1.] 

- Matriz Diagonal: 

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [-0. -0.  1.  0.]
 [-0. -0. -0.  1.]]


### Letra b)

Primeiramente, vamos carregar um vetor (`v3`) e uma matriz (`A3`) armazenados em um arquivo de texto nomeados `vetor3.txt` e `matriz3.txt`, respectivamente:

In [5]:
v3 = np.array(np.loadtxt("vetor3.txt", float))
A3 = np.array(np.loadtxt("matriz3.txt", float))

v2 = v3
A2 = A3

Definimos as variáveis `N` e `x`:

In [6]:
N = len(v)
x = np.zeros(N)

Agora implementamos o método da eliminação de Gauss por meio da função `GaussElim(A,v)`:

In [7]:
def GaussElim(A,v):
    for i in range(N):
        v[i] = v[i]/A[i,i]
        A[i,:] = A[i,:]/A[i,i]
        for j in range(i+1,N):
            mult = -(A[j,i])/A[i,i]
            A[j,:] = A[j,:] + mult*A[i,:]
            v[j] = v[j] + mult*v[i]
    v[N-1] = v[N-1]/A[N-1,N-1]
    A[N-1,N-1] = 1.0

    
    for i in range(N-1,-1,-1):
        x[i] = v[i]
        for j in range(i+1,N):
            x[i] -= A[i,j]*x[j]
    
    return x;

Agora printamos as soluções do sistema de equações presente no arquivo de texto usando o método de Gauss-Jordan e o tempo de execução:

In [8]:
print('\n1) Método de Gauss-Jordan:\n')
%time print(GaussJordan(A3,v3))


1) Método de Gauss-Jordan:

[  2.2313253    0.08192771  -0.49879518   0.10361446  -1.
  -2.           9.          -8.           0.          -3.
   2.          -6.           4.          -8.          -4.
  -2.           8.          -5.          -8.           1.
   8.          -2.           8.          -2.           1.
   2.           9.           1.           6.           0.
   0.           8.           2.           9.           8.
  -8.           8.          -7.          -8.          -3.
  -6.          -7.           5.          -1.          -9.
  -8.          -6.           9.          -9.          -2.
  -4.           6.          -8.           6.           1.
   7.           2.           4.          -5.           1.
   7.           9.           6.          -7.          -5.
   3.           9.           0.           5.           3.
  -7.           7.          -4.           0.           0.
   9.           0.          -4.           7.          -3.
  -5.         -10.          -5.          -9

Agora fazemos o mesmo que foi feito anteriormente, porém usando o método de eliminação de Gauss:

In [9]:
print('\n2) Método de eliminação Gaussiana:\n')
%time print(GaussElim(A2,v2))


2) Método de eliminação Gaussiana:

[ 2.2313253   0.08192771 -0.49879518  0.10361446]
Wall time: 1 ms


Como se bem pode ver, o método de eliminação Gaussiana foi executado mais rapidamente.

### Letra c)

No algoritmo QR, sabe-se de antemão que a matriz final é semelhante à matriz inicial. Entretanto, o mesmo não é verdade para o método de Gauss-Jordan.