# Lista de Exercícios VII

* Aluno : Gabriel Wendell Celestino Rocha
* Matrícula :  20190112149 

* Disciplina : Física Computacional I
* Professor : Leonardo Machado
* Data de Entrega : 03/11/2020

In [1]:
import numpy as np

## Problema 1

### Letra a)

Primeiramente, vamos escrever de forma explicita as equações para as outras três junções, serão elas:

$$\frac{V_{2}-V_{1}}{R}+\frac{V_{2}-V_{4}}{R}+\frac{V_{2}-0}{R}=0$$

$$\frac{V_{3}-V_{1}}{R}+\frac{V_{3}-V_{4}}{R}+\frac{V_{3}-V_{+}}{R}=0$$

$$\frac{V_{4}-V_{1}}{R}+\frac{V_{4}-V_{2}}{R}+\frac{V_{4}-V_{3}}{R}+\frac{V_{4}-0}{R}=0$$

Note que com as três equações acima obtemos o seguinte sistema de equações na forma matricial:

$$\begin{gather} \begin{pmatrix} 4 & -1 & -1 & -1\\ -1 & 3 & 0 & -1\\ -1 & 0 & 3 & -1\\ -1 & -1 & -1 & 4 \end{pmatrix} \begin{pmatrix} V_1\\ V_2\\ V_3\\ V_4 \end{pmatrix} = \begin{pmatrix} V_+ \\ 0\\ V_+ \\0 \end{pmatrix} \end{gather}$$

$\blacksquare$

### Letra b)

Primeiramente, note que desejamos resolver uma equação em $x$ do tipo $Ax=v$, onde:

$$A = \begin{pmatrix} 4 & -1 & -1 & -1\\ -1 & 3 & 0 & -1\\ -1 & 0 & 3 & -1\\ -1 & -1 & -1 & 4 \end{pmatrix}\text{    ;       }\text{   }v = \begin{pmatrix} V_+\\ 0\\ V_+ \\0 \end{pmatrix}$$

Desejamos resolver a equação matricial acima e obter as voltagens que constituem a solução do sistema de equações apresentados na **Letra a)**, para isso, vamos implementar o método da eliminação de Gauss. Primeiro definimos a nossa matriz quadrada `A` e o nosso vetor coluna `v`:

In [2]:
A = np.array ([[4,-1,-1,-1],
               [-1,3,0,-1],
               [-1,0,3,-1],
               [-1,-1,-1,4]],dtype = float)
v = np.array ([5 , 0 , 5 , 0],dtype = float)
N = len(v)

Agora implementamos o método de eliminação gaussiana:

In [3]:
for row in range (N):
    div = A[row,row]
    A[row,:] /= div
    v[row] /= div
    
    for i in range (row + 1 , N):
        mult = A[i,row]
        A[i , :] -= mult*A[row,:]
        v[i] -= mult*v[row]

Agora resolvemos a nossa equação matricial em `x`:

In [4]:
x = np.empty (N , dtype = float)

for row in range (N-1,-1,-1):
    # print (row)
    x[row] = v[row]
    for col in range (row+1 , N):
        x[row] -= A[row,col]*x[col]
        
print('x = ', x)

x =  [3.         1.66666667 3.33333333 2.        ]


### Letra c)

Agora vamos resolver a mesma equação matricial resolvida anteriormente usando a função `np.linal.solve()` do Numpy para podermos comparar com o resultado que obtivemos:

In [5]:
np.linalg.solve(A,v)

array([3.        , 1.66666667, 3.33333333, 2.        ])

Note que obtivemos basicamente o mesmo resultado usando a função `np.linalg.solve()`.

$\text{ }$

## Problema 2

Desejamos implementar o método de eliminação Gaussiana incluindo o método de pivotização para resolver os dois sistemas apresentados abaixo:

**Sistema 1:**

$$2w+x+4y+z=-4$$

$$3w+4x-y-z=3$$

$$w-4x+y+5z=9$$

$$2w-2x+y+3z=7$$

**Sistema 2:**

$$\begin{gather} \begin{pmatrix} 0 & 1 & 4 & 1\\ 3 & 4 & -1 & -1\\ 1 & -4 & 1 & 5\\ 2 & -2 & 1 & 3 \end{pmatrix} \begin{pmatrix} w\\ x\\ y\\ z \end{pmatrix} = \begin{pmatrix} -4 \\ 3\\ 9 \\7 \end{pmatrix} \end{gather}$$

Para resolver tais sistemas, fazemos um processo semelhante ao que foi feito no problema 1:

In [6]:
A = np.array ([[0,1,4,1],
               [3,4,-1,-1],
               [1,-4,1,5],
               [2,-2,1,3]],dtype = float)
v = np.array ([-4 , 3 , 9 , 7],dtype = float)
N = len(v)

Agora implementamos a eliminação Gaussiana, mas desta vez incluímos o método de pivotização (ou pivotagem):

In [7]:
for row in range (N):
    
    # Aqui implementamos o métoo de pivotização parcial
    for i in range (row+1,N):
        if abs(A[row,row]) < abs(A[i,row]):
            # Aqui comutamos as linhas
            A[[row,i],:] = A[[i,row],:]            
            v[[row,i]] = v[[i,row]] 
            
    div = A[row,row]
    A[row,:] /= div
    v[row] /= div
    
    for i in range (row + 1 , N):
        mult = A[i,row]
        A[i , :] -= mult*A[row,:]
        v[i] -= mult*v[row]

Por fim, resolvemos nossos sistemas em `x`:

In [8]:
x = np.empty (N , dtype = float)

for row in range (N-1,-1,-1):
    # print (row)
    x[row] = v[row]
    for col in range (row+1 , N):
        x[row] -= A[row,col]*x[col]
        
print('x = ', x)

x =  [ 1.61904762 -0.42857143 -1.23809524  1.38095238]


$\text{ }$

## Problema 3

### Letra a)

Nosso objetivo aqui é realizar a decomposição LU da matriz que representa o sistema abaixo:

$$2w+x+4y+z=-4$$

$$3w+4x-y-z=3$$

$$w-4x+y+5z=9$$

$$2w-2x+y+3z=7$$

Primeiramente, definimos a matriz quadrada `A` na qual desejamos aplicar a decomposição LU:

In [9]:
A = np.array ([[2,1,4,1],
              [3,4,-1,-1],
              [1,-4,1,5],
              [2,-2,1,3]],dtype = float)
N = len(A)

Agora comelamos a implementação da decomposição LU definindo `L` e `U` :

In [10]:
L = np.zeros_like (A,dtype = float)
U = np.zeros_like (A,dtype = float)

Analogamente ao que fizemos nos problemas anteriores, implementamos a eliminação Gaussiana:

In [11]:
for row in range (N):
    
    # A matriz L terá quase as mesmas colunas da matriz A. 
    # Isso será corrigido posteriormente.
    L[:,row] = A[:,row] 
    
    div = A[row,row]
    A[row,:] /= div
    
    for i in range (row + 1 , N):
        mult = A[i,row]
        A[i,:] -= mult*A[row,:]

Agora que a eliminação Gaussiana está concluída, `A` é uma matriz superior:

In [12]:
U = A

Agora vamos corrigir a matriz `L` e transformá-la numa matriz inferior:

In [13]:
for row in range (N):
    # Os elementos superiores possuem um índice de coluna sempre maior que o índice de linha (j > i)
    for col in range (row+1,N): 
        # Os elementos superiores são nulos.
        L[row,col] = 0 

Vamos começar printando a matriz `L`

In [14]:
print (' L : \n', L ,'\n\n')

 L : 
 [[  2.    0.    0.    0. ]
 [  3.    2.5   0.    0. ]
 [  1.   -4.5 -13.6   0. ]
 [  2.   -3.  -11.4  -1. ]] 




Agora printamos a matriz `U`

In [15]:
print (' U : \n', U ,'\n\n')

 U : 
 [[ 1.   0.5  2.   0.5]
 [ 0.   1.  -2.8 -1. ]
 [-0.  -0.   1.  -0. ]
 [-0.  -0.  -0.   1. ]] 




Por fim, mulitplicamos as matriz `L` e `U` com o auxílio da função `np.dot(L,U)` para obtermos a matriz original `A`:

In [16]:
print (' A : \n', np.dot(L,U) ,'\n\n')

 A : 
 [[ 2.  1.  4.  1.]
 [ 3.  4. -1. -1.]
 [ 1. -4.  1.  5.]
 [ 2. -2.  1.  3.]] 




### Letra b)

Vamos agora resolver o sistema apresentado usando o método descrito por Newman em seu livro *Computational Physics*. Primeiramente, definimos o vetor coluna `v` e os arrays nulos `x` e `y` que irão receber as soluções $x$ e $y$:

In [17]:
v = np.array ([-4,3,9,7],dtype = float)

y = np.empty (N,dtype = float)
x = np.empty (N,dtype = float)

Agora resolvemos o nosso sistema em `x` e em `y`:

In [18]:
for row in range (N-1,-1,-1):
    y[row] = v[row]
    for col in range (row+1 , N):
        y[row] -= L[row,col]*y[col]


for row in range (N-1,-1,-1):
    x[row] = y[row]
    for col in range (row+1 , N):
        x[row] -= U[row,col]*x[col]

Agora vamos printar os resultados:

In [19]:
print('x = ', x)
print('y = ', y)

x =  [-43.1  35.2   9.    7. ]
y =  [-4.  3.  9.  7.]


Agora vamos resolver o nosso sistema em `x` usando a função `np.linalg.solver(A,v)` para podermos comparar os
resultados obtidos:

In [20]:
print('Usando o Numpy :', '\n\n', 'x = ', np.linalg.solve(A,v))

Usando o Numpy : 

 x =  [-43.1  35.2   9.    7. ]


Analogamente ao que ocorreu no problema 1, obtivemos basicamente o mesmo resultado usando a função np.linalg.solve().

$\text{ }$

## Problema 4

Considerando o circuito em questão e considerando que as voltagens no pontos 1, 2 e 3 são da forma $V_{k}=x_{k}e^{i\omega t}$, com $k=1,2,3$, podemos aplicar a lei de Kircchoff em cada um dos três pontos, juntamente com as leis de Ohm e da capacitância e obter os seguintes resultados:

**Para o ponto 1:**

$$\frac{x_{1}e^{i\omega t}-x_{+}e^{i\omega t}}{R_{1}}+\frac{x_{1}e^{i\omega t}-0}{R_{4}}+C_{1}\frac{dV_{1}}{dt}-C_{1}\frac{dV_{2}}{dt}=0\implies$$

$$\frac{x_{1}e^{i\omega t}-x_{+}e^{i\omega t}}{R_{1}}+\frac{x_{1}e^{i\omega t}}{R_{4}}+i\omega C_{1}x_{1}e^{i\omega t}-i\omega C_{1}x_{2}e^{i\omega t}=0\implies$$

$$\therefore\text{  }\text{  }\boxed{\Bigg(\frac{1}{R_{1}}+\frac{1}{R_{4}}+i\omega C_{1}\Bigg)x_{1}-i\omega C_{1}x_{2}=\frac{x_{+}}{R_{1}}}$$

$\blacksquare$

**Para o ponto 2:**

$$\frac{x_{2}e^{i\omega t}-x_{+}e^{i\omega t}}{R_{2}}+\frac{x_{2}e^{i\omega t}-0}{R_{5}}+C_{1}\frac{dV_{2}}{dt}-C_{2}\frac{dV_{2}}{dt}-C_{2}\frac{dV_{3}}{dt}=0\implies$$

$$\frac{x_{2}e^{i\omega t}-x_{+}e^{i\omega t}}{R_{2}}+\frac{x_{2}e^{i\omega t}}{R_{5}}+i\omega C_{1}x_{2}e^{i\omega t}+i\omega C_{1}x_{1}e^{i\omega t}+i\omega C_{2}x_{2}e^{i\omega t}-i\omega C_{2}x_{3}e^{i\omega t}=0\implies$$

$$\therefore\text{  }\text{  }\boxed{\Bigg(\frac{1}{R_{2}}+\frac{1}{R_{5}}+i\omega C_{1}+i\omega C_{2}\Bigg)x_{2}-i\omega C_{1}x_{1}-i\omega C_{2}x_{3}=\frac{x_{+}}{R_{2}}}$$

$\blacksquare$

**Para o ponto 3:**

$$\frac{x_{3}e^{i\omega t}-x_{+}e^{i\omega t}}{R_{3}}+\frac{x_{3}e^{i\omega t}-0}{R_{6}}+C_{2}\frac{dV_{3}}{dt}-C_{2}\frac{dV_{3}}{dt}=0\implies$$

$$\frac{x_{3}e^{i\omega t}-x_{+}e^{i\omega t}}{R_{3}}+\frac{x_{3}e^{i\omega t}}{R_{6}}+i\omega C_{2}x_{3}e^{i\omega t}-i\omega C_{2}x_{2}e^{i\omega t}=0\implies$$

$$\therefore\text{  }\text{  }\boxed{\Bigg(\frac{1}{R_{3}}+\frac{1}{R_{6}}+i\omega C_{2}\Bigg)x_{3}-i\omega C_{2}x_{2}=\frac{x_{+}}{R_{3}}}$$

$\blacksquare$

Podemos escrever o nosso sistema de três equações na seguinte forma matricial:

$$\begin{gather} \begin{pmatrix} \frac{1}{R_1}+\frac{1}{R_4}+i\omega C_1 & -i\omega C_1 & 0\\ -i\omega C_1 & \frac{1}{R_2}+\frac{1}{R_5}+i\omega C_1+i\omega C_2 & -i\omega C_2 \\ 0 & i\omega C_2 & \frac{1}{R_3}+\frac{1}{R_6}+i\omega C_2 \end{pmatrix} \begin{pmatrix} x_1\\ x_2\\ x_3 \end{pmatrix} = \begin{pmatrix} \frac{x_+}{R_1}\\ \frac{x_+}{R_2}\\ \frac{x_+}{R_3} \end{pmatrix} \end{gather}$$

### Letra b)

Comecemos definindo algumas constantes fornecidas no enunciado e que serão usadas posteriormente:

In [21]:
R1 , R3 , R5 , = 1e3 , 1e3 , 1e3
R2 , R4 , R6 , = 2e3 , 2e3 , 2e3
C1 , C2 = 1e-6 , 0.5e-6
x_plus = 3
w = 1e3

Agora definimos a nossa matriz quadrada `A` e o vetor coluna `v`:

In [22]:
A = np.array ([[1/R1 + 1/R4 + 1j*w*C1 , -1j*w*C1 , 0],
              [-1j*w*C1 , 1/R2 + 1/R5 + 1j*w*C1 + 1j*w*C2 , -1j*w*C2],
              [0 , 1j*w*C2 , 1/R3 + 1/R6 + 1j*w*C2]],dtype = complex)

v = np.array ([x_plus/R1 , x_plus/R2 , x_plus/R3],dtype = complex)

Agora criamos uma função chamada `gauss_jordan(A, v)` que irá resolver o nosso sistema usando o método de Gauss-Jordan:

In [23]:
def gauss_jordan (A , v):
    
    N = len (v)
    AA = np.zeros ([N , N+1],dtype = complex)
    AA[:N,:N] = A
    AA[:,N] = v
    
    for row in range (N):
        AA[row,:] /= AA[row,row]
        
        for i in range (row):
            AA[i,:] -= AA[i,row]*AA[row,:]
            
        for i in range (row + 1,N):
            AA[i,:] -= AA[i,row]*AA[row,:]
    
    return AA[:,N]

**OBS:** No Python, usa-se a letra `j` para representar a parte complexa de um número>

Agora vamos printar a solução do sistema usando o método implementado logo acima:

In [24]:
print (gauss_jordan (A , v))

[1.80789159-0.1315265j  1.61060183+0.15663611j 1.68593065-1.09884416j]


Agora vamos resolver o mesmo sistema porém usando a função `np.linalg.solve()` para podermos comparar os resultados:

In [25]:
print(np.linalg.solve(A,v))

[1.80789159-0.1315265j  1.61060183+0.15663611j 1.68593065-1.09884416j]


Analogamente ao que ocorreu nos problemas 1 e 3, os resultados obtidos da resolução do sistema utilizando o método implementado e o que foram obtidos usando a função `np.linalg.solve()` foram os mesmo.